# Generated by Django 3.0.3 on 2020-04-24 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200424_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='post',
            name='quotes_name',
        ),
    ]
