# Generated by Django 3.0.3 on 2020-04-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200424_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('VueJs', 'VueJs')], default='', max_length=2000),
        ),
    ]
