# Generated by Django 3.0.3 on 2020-04-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200424_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('VueJs', 'VueJs'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('Machine learning', 'Machine learning'), ('JavaScript', 'JavaScript'), ('Jquery', 'Jquery'), ('Mongo DB', 'Mongo DB'), ('MySQL', 'MySQL')], default='', max_length=2000),
        ),
    ]
