# Generated by Django 3.0.3 on 2020-04-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200424_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_2',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
